-- MySQL Script generated by MySQL Workbench
-- Thu Apr  7 17:50:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PremierLeague
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PremierLeague
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PremierLeague` DEFAULT CHARACTER SET utf8 ;
USE `PremierLeague` ;

-- -----------------------------------------------------
-- Table `PremierLeague`.`Time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PremierLeague`.`Time` (
  `Nome` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NULL,
  `Estádio` VARCHAR(45) NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PremierLeague`.`Tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PremierLeague`.`Tecnico` (
  `idTecnico` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Nacionalidade` VARCHAR(45) NULL,
  `Data_Nascimento` DATE NULL,
  `Time_Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTecnico`),
  INDEX `fk_Tecnico_Time1_idx` (`Time_Nome` ASC) VISIBLE,
  CONSTRAINT `fk_Tecnico_Time1`
    FOREIGN KEY (`Time_Nome`)
    REFERENCES `PremierLeague`.`Time` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PremierLeague`.`Jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PremierLeague`.`Jogador` (
  `idJogador` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Nacionalidade` VARCHAR(45) NULL,
  `Data_Nascimento` DATE NULL,
  `Time_Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idJogador`),
  INDEX `fk_Jogador_Time1_idx` (`Time_Nome` ASC) VISIBLE,
  CONSTRAINT `fk_Jogador_Time1`
    FOREIGN KEY (`Time_Nome`)
    REFERENCES `PremierLeague`.`Time` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PremierLeague`.`Arbitro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PremierLeague`.`Arbitro` (
  `idÁrbitro` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Nacionalidade` VARCHAR(45) NULL,
  `Data_Nascimento` DATE NULL,
  PRIMARY KEY (`idÁrbitro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PremierLeague`.`Partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PremierLeague`.`Partida` (
  `idPartida` INT NOT NULL,
  `Estádio` VARCHAR(45) NULL,
  `Data` DATE NULL,
  `GolsCasa` INT NULL,
  `GolsVisitante` INT NULL,
  `Temporada` VARCHAR(45) NULL,
  `TimeCasa` VARCHAR(45) NOT NULL,
  `TimeVisitante` VARCHAR(45) NOT NULL,
  `Arbitro_idÁrbitro` INT NOT NULL,
  PRIMARY KEY (`idPartida`, `TimeCasa`, `TimeVisitante`),
  INDEX `fk_Partida_Time1_idx` (`TimeCasa` ASC) VISIBLE,
  INDEX `fk_Partida_Time2_idx` (`TimeVisitante` ASC) VISIBLE,
  INDEX `fk_Partida_Arbitro1_idx` (`Arbitro_idÁrbitro` ASC) VISIBLE,
  CONSTRAINT `fk_Partida_Time1`
    FOREIGN KEY (`TimeCasa`)
    REFERENCES `PremierLeague`.`Time` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partida_Time2`
    FOREIGN KEY (`TimeVisitante`)
    REFERENCES `PremierLeague`.`Time` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partida_Arbitro1`
    FOREIGN KEY (`Arbitro_idÁrbitro`)
    REFERENCES `PremierLeague`.`Arbitro` (`idÁrbitro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
